# Generated by Django 3.0.6 on 2020-05-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biwtapp', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
